Movies/Controllers/AdminProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Movies.Data;
using Movies.Models;

namespace Movies.Controllers
{
	[Authorize(Roles = "Admin")]
	public class AdminProductController : Controller
	{
		private readonly ApplicationDbContext _context;

		public AdminProductController(ApplicationDbContext context)
		{
			_context = context;
		}

		// GET: AdminProduct
		[HttpGet]
		public async Task<IActionResult> Index()
		{
			if (_context.Product == null)
				return Problem("Entity set 'ApplicationDbContext.Product'  is null.");

			var products = await _context.Product.ToListAsync();
			foreach (var product in products)
			{
				product.ProductImages = _context.ProductImage.Where(pi => pi.ProductId == product.Id).ToList();
				product.ProductCategories = _context.ProductCategory.Where(pc => pc.ProductId == product.Id).ToList();
			}
			ViewBag.Categories = _context.Category.ToList();
			return View(products);
		}

		// GET: AdminProduct/Details/5
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null || _context.Product == null)
			{
				return NotFound();
			}

			var product = await _context.Product
					.FirstOrDefaultAsync(m => m.Id == id);
			if (product == null)
			{
				return NotFound();
			}
			product.ProductImages = _context.ProductImage.Where(pi => pi.ProductId == product.Id).ToList();
			return View(product);
		}

		// GET: AdminProduct/Create
		public IActionResult Create()
		{
			return View();
		}

		// POST: AdminProduct/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("Id,Title,Description,Active,Quantity,Price")] Product product)
		{
			ModelState.Remove("ProductCategories");
			ModelState.Remove("OrderItems");
			ModelState.Remove("ProductImages");
			if (ModelState.IsValid)
			{
				_context.Add(product);
				await _context.SaveChangesAsync();
				return RedirectToAction(nameof(Index));
			}
			return View(product);
		}

		// GET: AdminProduct/Edit/5
		[HttpGet]
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null || _context.Product == null)
			{
				return NotFound();
			}
			var product = await _context.Product.FindAsync(id);
			if (product == null)
			{
				return NotFound();
			}
			product.ProductImages = _context.ProductImage.Where(pi => pi.ProductId == product.Id).ToList();
			product.ProductCategories = _context.ProductCategory.Where(pc => pc.ProductId == product.Id).ToList();
			ViewBag.Categories = _context.Category.ToList();
			return View(product);
		}

		// POST: AdminProduct/Edit/5
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Description,Active,Quantity,Price")] Product product)
		{
			if (id != product.Id)
			{
				return NotFound();
			}

			ModelState.Remove("ProductCategories");
			ModelState.Remove("OrderItems");
			ModelState.Remove("ProductImages");

			if (ModelState.IsValid)
			{
				try
				{
					_context.Update(product);
					await _context.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!ProductExists(product.Id))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction(nameof(Index));
			}
			return View(product);
		}

		[HttpPost]
		public async Task<IActionResult> Editcategory(int id)
		{
			if (_context.ProductCategory == null)
			{
				return Problem("Entity set 'ApplicationDbContext.ProductCategory'  is null.");
			}
			List<Category> categories = await _context.Category.ToListAsync();
			foreach (var cat in categories)
			{
				var checkbox = Request.Form[cat.Title];
				if (checkbox.Contains("true"))
				{
					var p = _context.ProductCategory.FirstOrDefault(x => x.CategoryId == cat.Id && x.ProductId == id);
					if (p == null) _context.ProductCategory.Add(new ProductCategory { ProductId = id, CategoryId = cat.Id });
				}
				else
				{
					var p = _context.ProductCategory.FirstOrDefault(x => x.CategoryId == cat.Id && x.ProductId == id);
					if (p != null) _context.ProductCategory.Remove(p);
				}
			}
			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Edit), new { id });
		}


		// GET: AdminProduct/Delete/5
		[HttpGet]
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null || _context.Product == null)
			{
				return NotFound();
			}

			var product = await _context.Product
					.FirstOrDefaultAsync(m => m.Id == id);
			if (product == null)
			{
				return NotFound();
			}

			return View(product);
		}

		// POST: AdminProduct/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			if (_context.Product == null)
			{
				return Problem("Entity set 'ApplicationDbContext.Product'  is null.");
			}
			var product = await _context.Product.FindAsync(id);
			if (product != null)
			{
				// ovo služi da se izbrišu svi zapisi iz tabele ProductImage koji imaju ProductId = product.Id
				// jer može biti više slika za jedan proizvod
				_context.ProductImage.RemoveRange(_context.ProductImage.Where(pc => pc.ProductId == product.Id));
				_context.Product.Remove(product);
			}

			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Index));
		}

		private bool ProductExists(int id)
		{
			return (_context.Product?.Any(e => e.Id == id)).GetValueOrDefault();
		}
	}
}

Movies/Controllers/AdminProductImagesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Movies.Data;
using Movies.Models;

namespace Movies.Controllers
{
	[Authorize(Roles = "Admin")]
	public class AdminProductImagesController : Controller
	{
		private readonly ApplicationDbContext _context;

		// konstruktor
		public AdminProductImagesController(ApplicationDbContext context)
		{
			_context = context;
		}

		// GET: AdminProductImages
		[HttpGet]
		public async Task<IActionResult> Index(int? id)
		{
			if (id == null)
			{
				return RedirectToAction("Index", "AdminProduct");
			}
			ViewBag.ProductId = id;
			if (_context.ProductImage == null) return Problem("Entity set 'ApplicationDbContext.ProductImage'  is null.");
			var product = await _context.ProductImage.ToListAsync();
			product = product.Where(p => p.ProductId == id).ToList();
			return View(product);
		}

		// GET: AdminProductImages/Details/5
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null || _context.ProductImage == null)
			{
				return NotFound();
			}

			var productImage = await _context.ProductImage.FirstOrDefaultAsync(m => m.Id == id);
			if (productImage == null)
			{
				return NotFound();
			}
			return View(productImage);
		}

		// GET: AdminProductImages/Create
		public IActionResult Create(int? id)
		{
			if (id == null)
			{
				return RedirectToAction("Index", "AdminProduct");
			}
			if (_context.Product.Count(p => p.Id == id) == 0) return RedirectToAction("Index", "AdminProduct");
			return View(new ProductImage() { ProductId = (int)id });
		}

		// POST: AdminProductImages/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("Id,ProductId,IsMainImage,Title,FileName")] ProductImage productImage)
		{
			ModelState.Remove("ProductTitle");
			if (HttpContext.Request.Form.Files.Count > 0) ModelState.Remove("FileName");
			if (ModelState.IsValid)
			{
				var imageFile = HttpContext.Request.Form.Files.FirstOrDefault();
				var uploadPath = System.IO.Path.Combine("wwwroot", "images", "products", productImage.ProductId.ToString());

				if (!System.IO.Directory.Exists(uploadPath))
				{
					System.IO.Directory.CreateDirectory(uploadPath);
				}

				if (imageFile != null)
				{
					var fileName = System.IO.Path.Combine(uploadPath, imageFile.FileName);
					using (var fileStream = new System.IO.FileStream(fileName, System.IO.FileMode.Create))
					{
						await imageFile.CopyToAsync(fileStream);
					}
					fileName = fileName.Replace("wwwroot\\", "/").Replace("\\", "/");
					productImage.FileName = fileName;
				}
				productImage.Id = 0;
				_context.Add(productImage);
				await _context.SaveChangesAsync();
				return RedirectToAction(nameof(Index), new { id = productImage.ProductId });
			}
			return View(productImage);
		}

		// GET: AdminProductImages/Edit/5
		public async Task<IActionResult> Edit(int? id)
		{
			//return RedirectToAction("Index", "AdminProduct");
			if (id == null || _context.ProductImage == null)
			{
				return NotFound();
			}
			var productImage = await _context.ProductImage.FindAsync(id);
			if (productImage == null)
			{
				return NotFound();
			}
			return View(productImage);
		}

		// POST: AdminProductImages/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, [Bind("Id,ProductId,IsMainImage,Title,FileName")] ProductImage productImage)
		{
			//return RedirectToAction("Index", "AdminProduct");
			if (id != productImage.Id)
			{
				return NotFound();
			}
			ModelState.Remove("ProductTitle");
			if (ModelState.IsValid)
			{
				try
				{
					_context.Update(productImage);
					await _context.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!ProductImageExists(productImage.Id))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction(nameof(Index));
			}
			return View(productImage);
		}

		// GET: AdminProductImages/Delete/5
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null || _context.ProductImage == null)
			{
				return NotFound();
			}
			var productImage = await _context.ProductImage
					.FirstOrDefaultAsync(m => m.Id == id);
			if (productImage == null)
			{
				return NotFound();
			}
			return View(productImage);
		}

		// POST: AdminProductImages/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			if (_context.ProductImage == null)
			{
				return Problem("Entity set 'ApplicationDbContext.ProductImage'  is null.");
			}
			var productImage = await _context.ProductImage.FindAsync(id);
			if (productImage != null)
			{
				var fileName = "wwwroot" + productImage.FileName.Replace("/", "\\");
				System.IO.File.Delete(fileName);
				_context.ProductImage.Remove(productImage);
			}

			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Index), new { id = productImage.ProductId });
		}

		private bool ProductImageExists(int id)
		{
			return (_context.ProductImage?.Any(e => e.Id == id)).GetValueOrDefault();
		}
	}
}

Movies/Views/AdminProduct/Create.cshtml
@model Movies.Models.Product

@{
	ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Product</h4>
<hr />
<div class="row">
	<div class="col-md-4">
		<form asp-action="Create">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<div class="form-group">
				<label asp-for="Title" class="control-label"></label>
				<input asp-for="Title" class="form-control" />
				<span asp-validation-for="Title" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Description" class="control-label"></label>
				<textarea asp-for="Description" class="form-control"></textarea>
				<span asp-validation-for="Description" class="text-danger"></span>
			</div>
			<div class="form-group form-check">
				<label class="form-check-label">
					<input class="form-check-input" asp-for="Active" /> @Html.DisplayNameFor(model => model.Active)
				</label>
			</div>
			<div class="form-group">
				<label asp-for="Quantity" class="control-label"></label>
				<input type="number" asp-for="Quantity" class="form-control" />
				<span asp-validation-for="Quantity" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Price" class="control-label"></label>
				<input type="number" asp-for="Price" class="form-control" />
				<span asp-validation-for="Price" class="text-danger"></span>
			</div>
			<div class="form-group">
				<input type="submit" value="Create" class="btn btn-primary" />
			</div>
		</form>
	</div>
</div>

<div>
	<a asp-action="Index">Back to List</a>
</div>

Movies/Views/AdminProduct/Delete.cshtml
@model Movies.Models.Product

@{
	ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
	<h4>Product</h4>
	<hr />
	<dl class="row">
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Title)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Title)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Description)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Description)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Active)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Active)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Quantity)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Quantity)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Price)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Price)
		</dd>
	</dl>

	<form asp-action="Delete">
		<input type="hidden" asp-for="Id" />
		<input type="submit" value="Delete" class="btn btn-danger" /> |
		<a asp-action="Index">Back to List</a>
	</form>
</div>

Movies/Views/AdminProduct/Details.cshtml
@model Movies.Models.Product

@{
	ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
	<h4>Product</h4>
	<hr />
	@if (Model.ProductImages != null)
	{
		<div class="row">
			@foreach (var image in Model.ProductImages)
			{
				<div class="col-sm-3">
					<img src="@image.FileName" alt="@Model.Title" height="100" />
				</div>
			}
		</div>
	}
	else
	{
		<img src="~/images/noimage.png" alt="No image" height="100" />
	}
	<hr />

	<dl class="row">
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Title)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Title)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Description)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Description)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Active)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Active)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Quantity)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Quantity)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Price)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Price)
		</dd>
	</dl>
</div>
<div>
	<a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
	<a asp-action="Index">Back to List</a>
</div>

Movies/Views/AdminProduct/Edit.cshtml
@model Movies.Models.Product

@{
	ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Product</h4>
<hr />
@if (Model.ProductImages != null)
{
	<div class="row">
		@foreach (var image in Model.ProductImages)
		{
			<div class="col-sm-3">
				<img src="@image.FileName" alt="@Model.Title" height="100" />
			</div>
		}
	</div>
}
else
{
	<img src="~/images/noimage.png" alt="No image" height="100" />
}

<a asp-controller="AdminProductImages" asp-action="Index" asp-route-id="@Model.Id" />Edit Image</a>

<hr />
<div class="row">
	<div class="col-md-4">
		<form asp-action="Edit">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<input type="hidden" asp-for="Id" />
			<div class="form-group">
				<label asp-for="Title" class="control-label"></label>
				<input asp-for="Title" class="form-control" />
				<span asp-validation-for="Title" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Description" class="control-label"></label>
				<textarea asp-for="Description" class="form-control"> </textarea>
				<span asp-validation-for="Description" class="text-danger"></span>
			</div>
			<div class="form-group form-check">
				<label class="form-check-label">
					<input class="form-check-input" asp-for="Active" /> @Html.DisplayNameFor(model => model.Active)
				</label>
			</div>
			<div class="form-group">
				<label asp-for="Quantity" class="control-label"></label>
				<input asp-for="Quantity" class="form-control" />
				<span asp-validation-for="Quantity" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Price" class="control-label"></label>
				<input asp-for="Price" class="form-control" />
				<span asp-validation-for="Price" class="text-danger"></span>
			</div>
			<div class="form-group">
				<input type="submit" value="Save" class="btn btn-primary" />
			</div>
		</form>
	</div>
	<div class="col-md-4">
		<form asp-action="Editcategory">
			<input type="hidden" asp-for="Id" />
			<label>Categories</label>
			@foreach (Category cat in ViewBag.Categories)
			{
				<div class="form-group">
					@Html.CheckBox(cat.Title, Model.ProductCategories.Count(x=> x.CategoryId == cat.Id) > 0)
					@Html.Label(cat.Title)
				</div>
			}
			<div class="form-group mt-2">
				<input type="submit" value="Save Categories" class="btn btn-primary" />
			</div>
		</form>
	</div>
</div>

<div>
	<a asp-action="Index">Back to List</a>
</div>

Movies/Views/AdminProduct/Index.cshtml
@model IEnumerable<Movies.Models.Product>

@{
	ViewData["Title"] = "Index";
}

<h1>Index Admin product</h1>

<p>
	<a asp-action="Create">Create New</a>
</p>
<table class="table">
	<thead>
		<tr>
			<th>
				@Html.DisplayNameFor(model => model.Title)
			</th>
			<th>
				Title Image
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Description)
			</th>
			<th>
				Category
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Active)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Quantity)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Price)
			</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model)
		{
			<tr>
				<td>
					@Html.DisplayFor(modelItem => item.Title)
				</td>
				<td>
					@{
						try
						{
							var image = item.ProductImages.FirstOrDefault(x => x.IsMainImage == true);
							if (image != null)
							{
								<img src="@image.FileName" alt="@item.Title" height="100" />
							}
							else
							{
								<img src="~/images/noimage.png" alt="No image" height="100" />
							}
						}
						catch (Exception)
						{
							<img src="~/images/noimage.png" alt="No image" height="100" />
						}
					}
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Description)
				</td>
				<td>
					@foreach (var category in item.ProductCategories)
					{
						var cat = (ViewBag.Categories as List<Category>).FirstOrDefault(x => x.Id == category.CategoryId);
						<span>@cat.Title</span> <br />
					}
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Active)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Quantity)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Price)
				</td>
				<td>
					<a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
					<a asp-action="Details" asp-route-id="@item.Id">Details</a> |
					<a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
				</td>
			</tr>
		}
	</tbody>
</table>