Movies/Controllers/AdminCategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Movies.Data;
using Movies.Models;

namespace Movies.Controllers
{
	[Authorize]
	public class AdminCategoryController : Controller
	{
		private readonly ApplicationDbContext _context;

		public AdminCategoryController(ApplicationDbContext context)
		{
			_context = context;
		}

		// GET: AdminCategory
		public async Task<IActionResult> Index()
		{
			return _context.Category != null ?
									View(await _context.Category.ToListAsync()) :
									Problem("Entity set 'ApplicationDbContext.Category'  is null.");
		}

		// GET: AdminCategory/Details/5
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null || _context.Category == null)
			{
				return NotFound();
			}

			var category = await _context.Category
					.FirstOrDefaultAsync(m => m.Id == id);
			if (category == null)
			{
				return NotFound();
			}

			return View(category);
		}

		// GET: AdminCategory/Create
		public IActionResult Create()
		{
			return View();
		}

		// POST: AdminCategory/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("Id,Title")] Category category)
		{
			ModelState.Remove("ProductCategories");
			if (ModelState.IsValid)
			{
				_context.Add(category);
				await _context.SaveChangesAsync();
				return RedirectToAction(nameof(Index));
			}
			return View(category);
		}

		// GET: AdminCategory/Edit/5
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null || _context.Category == null)
			{
				return NotFound();
			}

			var category = await _context.Category.FindAsync(id);
			if (category == null)
			{
				return NotFound();
			}
			return View(category);
		}

		// POST: AdminCategory/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, [Bind("Id,Title")] Category category)
		{
			ModelState.Remove("ProductCategories");
			if (id != category.Id)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				try
				{
					_context.Update(category);
					await _context.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!CategoryExists(category.Id))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction(nameof(Index));
			}
			return View(category);
		}

		// GET: AdminCategory/Delete/5
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null || _context.Category == null)
			{
				return NotFound();
			}

			var category = await _context.Category
					.FirstOrDefaultAsync(m => m.Id == id);
			if (category == null)
			{
				return NotFound();
			}

			return View(category);
		}

		// POST: AdminCategory/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			if (_context.Category == null)
			{
				return Problem("Entity set 'ApplicationDbContext.Category'  is null.");
			}
			var category = await _context.Category.FindAsync(id);
			if (category != null)
			{
				_context.Category.Remove(category);
			}

			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Index));
		}

		private bool CategoryExists(int id)
		{
			return (_context.Category?.Any(e => e.Id == id)).GetValueOrDefault();
		}
	}
}

Movies/Controllers/AdminOrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Movies.Data;
using Movies.Models;

namespace Movies.Controllers
{
	[Authorize(Roles = "Admin")]
	public class AdminOrderController : Controller
	{
		private readonly ApplicationDbContext _context;

		public AdminOrderController(ApplicationDbContext context)
		{
			_context = context;
		}


		// GET: AdminOrder
		public async Task<IActionResult> Index()
		{
			return _context.Order != null ?
									View(await _context.Order.ToListAsync()) :
									Problem("Entity set 'ApplicationDbContext.Order'  is null.");
		}

		// GET: AdminOrder/Details/5
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null || _context.Order == null)
			{
				return NotFound();
			}

			var order = await _context.Order.FirstOrDefaultAsync(m => m.Id == id);
			if (order == null)
			{
				return NotFound();
			}

			// izvlaci sve order iteme za odredjeni order
			order.OrderItems = (
			from order_item in _context.OrderItem
			where order_item.OrderId == order.Id
			select new OrderItem
			{
				Id = order_item.Id,
				OrderId = order_item.OrderId,
				ProductId = order_item.ProductId,
				Quantity = order_item.Quantity,
				Price = order_item.Price,
				ProductTitle = (from product in _context.Product
												where product.Id == order_item.ProductId
												select product.Title).FirstOrDefault()
			}).ToList();
			return View(order);
		}

		// GET: AdminOrder/Edit/5
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null || _context.Order == null)
			{
				return NotFound();
			}

			var order = await _context.Order.FirstOrDefaultAsync(m => m.Id == id);
			if (order == null)
			{
				return NotFound();
			}

			//order.OrederItems = ItemsForOrder((int)id);

			order.OrderItems = (
			from order_item in _context.OrderItem
			where order_item.OrderId == order.Id
			select new OrderItem
			{
				Id = order_item.Id,
				OrderId = order_item.OrderId,
				ProductId = order_item.ProductId,
				Quantity = order_item.Quantity,
				Price = order_item.Price,
				ProductTitle = (from product in _context.Product
												where product.Id == order_item.ProductId
												select product.Title).FirstOrDefault()
			}).ToList();

			return View(order);
		}

		// POST: AdminOrder/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, [Bind("Id,DateCreated,Total,BillingFirstName,BillingLastName,BillingEmail,BillingPhone,BillingAddress,BillingCity,BillingPostalCode,BillingCountry,ShippingFirstName,ShippingLastName,ShippingEmail,ShippingPhone,ShippingAddress,ShippingCity,ShippingPostalCode,ShippingCountry,Message,UserId")] Order order)
		{
			if (id != order.Id)
			{
				return NotFound();
			}
			ModelState.Remove("OrderItems");

			if (ModelState.IsValid)
			{
				try
				{
					_context.Update(order);
					await _context.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!OrderExists(order.Id))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction(nameof(Index));
			}
			return View(order);
		}

		// GET: AdminOrder/Delete/5
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null || _context.Order == null)
			{
				return NotFound();
			}

			var order = await _context.Order
					.FirstOrDefaultAsync(m => m.Id == id);
			if (order == null)
			{
				return NotFound();
			}

			order.OrderItems = (
				from order_item in _context.OrderItem
				where order_item.OrderId == order.Id
				select new OrderItem
				{
					Id = order_item.Id,
					OrderId = order_item.OrderId,
					ProductId = order_item.ProductId,
					Quantity = order_item.Quantity,
					Price = order_item.Price,
					ProductTitle = (from product in _context.Product
													where product.Id == order_item.ProductId
													select product.Title).FirstOrDefault()
				}).ToList();

			return View(order);
		}

		// POST: AdminOrder/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			if (_context.Order == null)
			{
				return Problem("Entity set 'ApplicationDbContext.Order'  is null.");
			}
			var order = await _context.Order.FindAsync(id);
			if (order != null)
			{
				foreach (var order_item in _context.OrderItem.Where(oi => oi.OrderId == order.Id))
				{
					_context.Product.Find(order_item.ProductId).Quantity += order_item.Quantity;
					_context.OrderItem.Remove(order_item);
				}
				_context.Order.Remove(order);
			}

			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Index));
		}

		private bool OrderExists(int id)
		{
			return (_context.Order?.Any(e => e.Id == id)).GetValueOrDefault();
		}
	}
}

Movies/Controllers/AdminProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Movies.Data;
using Movies.Models;

namespace Movies.Controllers
{
	[Authorize(Roles = "Admin")]
	public class AdminProductController : Controller
	{
		private readonly ApplicationDbContext _context;

		public AdminProductController(ApplicationDbContext context)
		{
			_context = context;
		}

		// GET: AdminProduct
		[HttpGet]
		public async Task<IActionResult> Index()
		{
			if (_context.Product == null)
				return Problem("Entity set 'ApplicationDbContext.Product'  is null.");

			var products = await _context.Product.ToListAsync();
			foreach (var product in products)
			{
				product.ProductImages = _context.ProductImage.Where(pi => pi.ProductId == product.Id).ToList();
				product.ProductCategories = _context.ProductCategory.Where(pc => pc.ProductId == product.Id).ToList();
			}
			ViewBag.Categories = _context.Category.ToList();
			return View(products);
		}

		// GET: AdminProduct/Details/5
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null || _context.Product == null)
			{
				return NotFound();
			}

			var product = await _context.Product
					.FirstOrDefaultAsync(m => m.Id == id);
			if (product == null)
			{
				return NotFound();
			}
			product.ProductImages = _context.ProductImage.Where(pi => pi.ProductId == product.Id).ToList();
			return View(product);
		}

		// GET: AdminProduct/Create
		public IActionResult Create()
		{
			return View();
		}

		// POST: AdminProduct/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("Id,Title,Description,Active,Quantity,Price")] Product product)
		{
			ModelState.Remove("ProductCategories");
			ModelState.Remove("OrderItems");
			ModelState.Remove("ProductImages");
			if (ModelState.IsValid)
			{
				_context.Add(product);
				await _context.SaveChangesAsync();
				return RedirectToAction(nameof(Index));
			}
			return View(product);
		}

		// GET: AdminProduct/Edit/5
		[HttpGet]
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null || _context.Product == null)
			{
				return NotFound();
			}
			var product = await _context.Product.FindAsync(id);
			if (product == null)
			{
				return NotFound();
			}
			product.ProductImages = _context.ProductImage.Where(pi => pi.ProductId == product.Id).ToList();
			product.ProductCategories = _context.ProductCategory.Where(pc => pc.ProductId == product.Id).ToList();
			ViewBag.Categories = _context.Category.ToList();
			return View(product);
		}

		// POST: AdminProduct/Edit/5
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Description,Active,Quantity,Price")] Product product)
		{
			if (id != product.Id)
			{
				return NotFound();
			}

			ModelState.Remove("ProductCategories");
			ModelState.Remove("OrderItems");
			ModelState.Remove("ProductImages");

			if (ModelState.IsValid)
			{
				try
				{
					_context.Update(product);
					await _context.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!ProductExists(product.Id))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction(nameof(Index));
			}
			return View(product);
		}

		[HttpPost]
		public async Task<IActionResult> Editcategory(int id)
		{
			if (_context.ProductCategory == null)
			{
				return Problem("Entity set 'ApplicationDbContext.ProductCategory'  is null.");
			}
			List<Category> categories = await _context.Category.ToListAsync();
			foreach (var cat in categories)
			{
				var checkbox = Request.Form[cat.Title];
				if (checkbox.Contains("true"))
				{
					var p = _context.ProductCategory.FirstOrDefault(x => x.CategoryId == cat.Id && x.ProductId == id);
					if (p == null) _context.ProductCategory.Add(new ProductCategory { ProductId = id, CategoryId = cat.Id });
				}
				else
				{
					var p = _context.ProductCategory.FirstOrDefault(x => x.CategoryId == cat.Id && x.ProductId == id);
					if (p != null) _context.ProductCategory.Remove(p);
				}
			}
			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Edit), new { id });
		}


		// GET: AdminProduct/Delete/5
		[HttpGet]
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null || _context.Product == null)
			{
				return NotFound();
			}

			var product = await _context.Product
					.FirstOrDefaultAsync(m => m.Id == id);
			if (product == null)
			{
				return NotFound();
			}

			return View(product);
		}

		// POST: AdminProduct/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			if (_context.Product == null)
			{
				return Problem("Entity set 'ApplicationDbContext.Product'  is null.");
			}
			var product = await _context.Product.FindAsync(id);
			if (product != null)
			{
				// ovo služi da se izbrišu svi zapisi iz tabele ProductImage koji imaju ProductId = product.Id
				// jer može biti više slika za jedan proizvod
				_context.ProductImage.RemoveRange(_context.ProductImage.Where(pc => pc.ProductId == product.Id));
				_context.Product.Remove(product);
			}

			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Index));
		}

		private bool ProductExists(int id)
		{
			return (_context.Product?.Any(e => e.Id == id)).GetValueOrDefault();
		}
	}
}

Movies/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using Movies.Data;
using Movies.Extensions;

namespace Movies.Controllers
{
	public class CartController : Controller
	{
		public const string SessionKeyName = "_cart";
		private readonly ApplicationDbContext _context;


		public CartController(ApplicationDbContext context)
		{
			_context = context;
		}

		public IActionResult Index()
		{
			List<CartItem> cart = HttpContext.Session.GetObjectFromJson<List<CartItem>>(SessionKeyName);
			if (cart == null)
			{
				cart = new List<CartItem>();
			}
			decimal total = 0;
			foreach (CartItem item in cart)
			{
				item.Product.ProductImages = _context.ProductImage.Where(pi => pi.ProductId == item.Product.Id).ToList();
				total += item.getTotal();
			}
			ViewBag.CartTotal = total;
			return View(cart);
		}


		[HttpPost]
		public IActionResult AddToCart(int productId)
		{
			List<CartItem> cart = HttpContext.Session.GetObjectFromJson<List<CartItem>>(SessionKeyName);
			if (cart == null) cart = new List<CartItem>();

			if (cart.Count == 0)
			{
				var item = new CartItem()
				{
					Product = _context.Product.Find(productId),
					Quantity = 1
				};
				cart.Add(item);

				HttpContext.Session.SetObjectAsJson(SessionKeyName, cart);
			}
			else
			{
				// Cart is not empty
				bool found = false;
				foreach (CartItem item in cart)
				{
					if (item.Product.Id == productId)
					{
						// Item found in cart, so increment quantity
						item.Quantity++;
						found = true;
						break;
					}
				}
				if (!found)
				{
					// Item not found in cart, so add new item to cart!
					CartItem item = new CartItem()
					{
						Product = _context.Product.Find(productId),
						Quantity = 1
					};
					cart.Add(item);
				}
				HttpContext.Session.SetObjectAsJson(SessionKeyName, cart);
			}
			return RedirectToAction("Index");
		}

		[HttpPost]
		public IActionResult ChangeCartItemQuantity(int productId, decimal quantity)
		{
			if (quantity <= 0) return RedirectToAction("RemoveFromCart", new { productId = productId });

			List<CartItem> cart = HttpContext.Session.GetObjectFromJson<List<CartItem>>(SessionKeyName);
			foreach (CartItem item in cart)
			{
				if (item.Product.Id == productId)
				{
					item.Quantity = quantity;
					break;
				}
			}

			HttpContext.Session.SetObjectAsJson(SessionKeyName, cart);
			return RedirectToAction("Index");
		}

		public IActionResult RemoveFromCart(int productId)
		{
			List<CartItem> cart = HttpContext.Session.GetObjectFromJson<List<CartItem>>(SessionKeyName);
			cart.RemoveAll(item => item.Product.Id == productId);
			HttpContext.Session.SetObjectAsJson(SessionKeyName, cart);
			return RedirectToAction("Index");
		}
	}
}

Movies/Views/Shared/_AdminMenuPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using Movies.Data
@inject SignInManager<AppUser> SignInManager
@inject UserManager<AppUser> UserManager

@if (SignInManager.IsSignedIn(User) && await UserManager.IsInRoleAsync(UserManager.GetUserAsync(User).Result, "admin"))
{
	<li class="nav-item dropdown">
		<a class="nav-link dropdown-toggle text-dark" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Admin</a>
		<div class="dropdown-menu" style="">

			<a class="dropdown-item" asp-controller="AdminCategory" asp-controller="Category" asp-action="Index">Categories</a>
			<a class="dropdown-item" asp-controller="AdminProduct" asp-controller="Product" asp-action="Index">Products</a>
			<div class="dropdown-divider"></div>
			<a class="dropdown-item" asp-controller="AdminOrder" asp-action="Index">Orders</a>
		</div>
	</li>
}

Movies/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Movies</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/Movies.styles.css" asp-append-version="true" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Movies</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
								aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
						</li>
						<partial name="_PublicMenuPartial" />
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
						</li>
						<partial name="_AdminMenuPartial" />
					</ul>
					<partial name="_LoginPartial" />
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2023 - Movies - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Movies/Views/Shared/_OrderItemsPartial.cshtml
@model List<Movies.Models.OrderItem>

<table class="table">
	<thred>

		<th scope="col">Product</th>
		<th scope="col">Quantity</th>
		<th scope="col">Price</th>
		<th scope="col">Total</th>
	</thred>
	<tbody>
		@foreach (var item in Model)
		{
			<tr>
				<td>@Html.DisplayFor(modelItem => item.ProductTitle)</td>
				<td>@Html.DisplayFor(modelItem => item.Quantity)</td>
				<td>@Html.DisplayFor(modelItem => item.Price)</td>
				<td>@((item.Price * item.Quantity).ToString("0.00")) €</td>
			</tr>
		}
	</tbody>

</table>

Movies/Views/Shared/_PublicMenuPartial.cshtml
@using Microsoft.AspNetCore.Http
@using Movies.Extensions
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
<li class="nav-item">
	<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Product" asp-route-id="">Products</a>
</li>



<li class="nav-item">
	@{
		var cart = HttpContextAccessor.HttpContext.Session.GetObjectFromJson<List<Movies.Extensions.CartItem>>("_cart");
		int broj = 0;
		if (cart != null)
		{
			broj = cart.Count();
		}
		string ispis = " Cart ";
		if (broj > 0)
		{
			ispis += "(" + broj + ")";
		}
	}
	<a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Index">
		@ispis
	</a>
</li>