Movies/Controllers/AdminOrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Movies.Data;
using Movies.Models;

namespace Movies.Controllers
{
	[Authorize(Roles = "Admin")]
	public class AdminOrderController : Controller
	{
		private readonly ApplicationDbContext _context;

		public AdminOrderController(ApplicationDbContext context)
		{
			_context = context;
		}


		// GET: AdminOrder
		public async Task<IActionResult> Index()
		{
			return _context.Order != null ?
									View(await _context.Order.ToListAsync()) :
									Problem("Entity set 'ApplicationDbContext.Order'  is null.");
		}

		// GET: AdminOrder/Details/5
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null || _context.Order == null)
			{
				return NotFound();
			}

			var order = await _context.Order.FirstOrDefaultAsync(m => m.Id == id);
			if (order == null)
			{
				return NotFound();
			}

			// izvlaci sve order iteme za odredjeni order
			order.OrderItems = (
			from order_item in _context.OrderItem
			where order_item.OrderId == order.Id
			select new OrderItem
			{
				Id = order_item.Id,
				OrderId = order_item.OrderId,
				ProductId = order_item.ProductId,
				Quantity = order_item.Quantity,
				Price = order_item.Price,
				ProductTitle = (from product in _context.Product
												where product.Id == order_item.ProductId
												select product.Title).FirstOrDefault()
			}).ToList();
			return View(order);
		}

		// GET: AdminOrder/Edit/5
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null || _context.Order == null)
			{
				return NotFound();
			}

			var order = await _context.Order.FirstOrDefaultAsync(m => m.Id == id);
			if (order == null)
			{
				return NotFound();
			}

			//order.OrederItems = ItemsForOrder((int)id);

			order.OrderItems = (
			from order_item in _context.OrderItem
			where order_item.OrderId == order.Id
			select new OrderItem
			{
				Id = order_item.Id,
				OrderId = order_item.OrderId,
				ProductId = order_item.ProductId,
				Quantity = order_item.Quantity,
				Price = order_item.Price,
				ProductTitle = (from product in _context.Product
												where product.Id == order_item.ProductId
												select product.Title).FirstOrDefault()
			}).ToList();

			return View(order);
		}

		// POST: AdminOrder/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, [Bind("Id,DateCreated,Total,BillingFirstName,BillingLastName,BillingEmail,BillingPhone,BillingAddress,BillingCity,BillingPostalCode,BillingCountry,ShippingFirstName,ShippingLastName,ShippingEmail,ShippingPhone,ShippingAddress,ShippingCity,ShippingPostalCode,ShippingCountry,Message,UserId")] Order order)
		{
			if (id != order.Id)
			{
				return NotFound();
			}
			ModelState.Remove("OrderItems");

			if (ModelState.IsValid)
			{
				try
				{
					_context.Update(order);
					await _context.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!OrderExists(order.Id))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction(nameof(Index));
			}
			return View(order);
		}

		// GET: AdminOrder/Delete/5
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null || _context.Order == null)
			{
				return NotFound();
			}

			var order = await _context.Order
					.FirstOrDefaultAsync(m => m.Id == id);
			if (order == null)
			{
				return NotFound();
			}

			order.OrderItems = (
				from order_item in _context.OrderItem
				where order_item.OrderId == order.Id
				select new OrderItem
				{
					Id = order_item.Id,
					OrderId = order_item.OrderId,
					ProductId = order_item.ProductId,
					Quantity = order_item.Quantity,
					Price = order_item.Price,
					ProductTitle = (from product in _context.Product
													where product.Id == order_item.ProductId
													select product.Title).FirstOrDefault()
				}).ToList();

			return View(order);
		}

		// POST: AdminOrder/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			if (_context.Order == null)
			{
				return Problem("Entity set 'ApplicationDbContext.Order'  is null.");
			}
			var order = await _context.Order.FindAsync(id);
			if (order != null)
			{
				foreach (var order_item in _context.OrderItem.Where(oi => oi.OrderId == order.Id))
				{
					_context.Product.Find(order_item.ProductId).Quantity += order_item.Quantity;
					_context.OrderItem.Remove(order_item);
				}
				_context.Order.Remove(order);
			}

			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Index));
		}

		private bool OrderExists(int id)
		{
			return (_context.Order?.Any(e => e.Id == id)).GetValueOrDefault();
		}
	}
}

Movies/Controllers/AdminOrderItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Movies.Data;
using Movies.Models;

namespace Movies.Controllers
{
	[Authorize(Roles = "Admin")]
	public class AdminOrderItemController : Controller
	{
		private readonly ApplicationDbContext _context;

		public AdminOrderItemController(ApplicationDbContext context)
		{
			_context = context;
		}

		// GET: AdminOrderItem
		public async Task<IActionResult> Index(int? id)
		{
			if (id == null)
			{
				return RedirectToAction("Index", "AdminOrder");
			}
			var orderItems = await _context.OrderItem.Where(o => o.OrderId == id).ToListAsync();

			foreach (var item in orderItems)
			{
				item.ProductTitle = (from product in _context.Product
														 where product.Id == item.ProductId
														 select product.Title).FirstOrDefault();
			}


			return View(orderItems);
		}

		// GET: AdminOrderItem/Details/5
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null || _context.OrderItem == null)
			{
				return NotFound();
			}

			var orderItem = await _context.OrderItem
					.FirstOrDefaultAsync(m => m.Id == id);
			if (orderItem == null)
			{
				return NotFound();
			}
			orderItem.ProductTitle = (from product in _context.Product
																where product.Id == orderItem.ProductId
																select product.Title).FirstOrDefault();

			return View(orderItem);
		}

		// GET: AdminOrderItem/Create
		public IActionResult Create()
		{
			return View();
		}

		// POST: AdminOrderItem/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("Id,OrderId,ProductId,Quantity,Price")] OrderItem orderItem)
		{
			if (ModelState.IsValid)
			{
				_context.Add(orderItem);
				await _context.SaveChangesAsync();
				return RedirectToAction(nameof(Index));
			}
			return View(orderItem);
		}

		// GET: AdminOrderItem/Edit/5
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null || _context.OrderItem == null)
			{
				return NotFound();
			}

			var orderItem = await _context.OrderItem.FindAsync(id);
			if (orderItem == null)
			{
				return NotFound();
			}
			orderItem.ProductTitle = (from product in _context.Product
																where product.Id == orderItem.ProductId
																select product.Title).FirstOrDefault();
			return View(orderItem);
		}

		// POST: AdminOrderItem/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, [Bind("Id,OrderId,ProductId,Quantity,Price")] OrderItem orderItem)
		{
			if (id != orderItem.Id)
			{
				return NotFound();
			}

			if (orderItem.Price <= 0)
			{
				ModelState.AddModelError("Price", "Price must be greater than 0");
			}

			if (orderItem.Quantity <= 0)
			{
				ModelState.AddModelError("Quantity", "Quantity must be greater than 0");
			}
			ModelState.Remove("ProductTitle");


			if (ModelState.IsValid)
			{
				try
				{
					var old_OrderItem = await _context.OrderItem.FindAsync(id);
					var quantitity_diff = orderItem.Quantity - old_OrderItem.Quantity;
					var price_diff = orderItem.Price - old_OrderItem.Price;
					if (quantitity_diff < 0) // ako se smanjuje kolicina
					{
						_context.Product.Find(orderItem.ProductId).Quantity += Math.Abs(quantitity_diff);
					}

					if (quantitity_diff > 0) // ako se povecava kolicina
					{
						var available_quantity = _context.Product.Find(orderItem.ProductId).Quantity;
						if (available_quantity < quantitity_diff)
						{
							ModelState.AddModelError("Quantity", "Not enough products in stock");
							orderItem.ProductTitle = (from product in _context.Product
																				where product.Id == orderItem.ProductId
																				select product.Title).FirstOrDefault();
							return View(orderItem);
						}
						_context.Product.Find(orderItem.ProductId).Quantity -= quantitity_diff;
					}
					if (price_diff != 0 || quantitity_diff != 0)
					{
						var old_price = old_OrderItem.Price * old_OrderItem.Quantity;
						var new_price = orderItem.Price * orderItem.Quantity;
						_context.Order.Find(orderItem.OrderId).Total += new_price - old_price;
					}
					old_OrderItem.Quantity = orderItem.Quantity;
					old_OrderItem.Price = orderItem.Price;
					//_context.Update(orderItem);
					await _context.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!OrderItemExists(orderItem.Id))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction(nameof(Index), new { id = orderItem.OrderId });
			}
			orderItem.ProductTitle = (from product in _context.Product
																where product.Id == orderItem.ProductId
																select product.Title).FirstOrDefault();
			return View(orderItem);
		}

		// GET: AdminOrderItem/Delete/5
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null || _context.OrderItem == null)
			{
				return NotFound();
			}

			var orderItem = await _context.OrderItem
					.FirstOrDefaultAsync(m => m.Id == id);
			if (orderItem == null)
			{
				return NotFound();
			}

			return View(orderItem);
		}

		// POST: AdminOrderItem/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			if (_context.OrderItem == null)
			{
				return Problem("Entity set 'ApplicationDbContext.OrderItem'  is null.");
			}
			var orderItem = await _context.OrderItem.FindAsync(id);
			int? orderid = orderItem.OrderId;
			if (orderItem != null)
			{
				// vratiti kolicinu proizvoda na stanje
				_context.Product.Find(orderItem.ProductId).Quantity += orderItem.Quantity;
				// smanjiti ukupnu cijenu narudzbe
				_context.Order.Find(orderItem.OrderId).Total -= orderItem.Price * orderItem.Quantity;

				_context.OrderItem.Remove(orderItem);
			}

			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Index), new { id = orderid });
		}

		private bool OrderItemExists(int id)
		{
			return (_context.OrderItem?.Any(e => e.Id == id)).GetValueOrDefault();
		}
	}
}

Movies/Views/AdminOrder/Create.cshtml
@model Movies.Models.Order

@{
	ViewData["Title"] = "Create xxxxxx";
}

<h1>Create</h1>

<h4>Order</h4>
<hr />
<div class="row">
	<div class="col-md-4">
		<form asp-action="Create">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<div class="form-group">
				<label asp-for="DateCreated" class="control-label"></label>
				<input asp-for="DateCreated" class="form-control" />
				<span asp-validation-for="DateCreated" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Total" class="control-label"></label>
				<input asp-for="Total" class="form-control" />
				<span asp-validation-for="Total" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="BillingFirstName" class="control-label"></label>
				<input asp-for="BillingFirstName" class="form-control" />
				<span asp-validation-for="BillingFirstName" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="BillingLastName" class="control-label"></label>
				<input asp-for="BillingLastName" class="form-control" />
				<span asp-validation-for="BillingLastName" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="BillingEmail" class="control-label"></label>
				<input asp-for="BillingEmail" class="form-control" />
				<span asp-validation-for="BillingEmail" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="BillingPhone" class="control-label"></label>
				<input asp-for="BillingPhone" class="form-control" />
				<span asp-validation-for="BillingPhone" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="BillingAddress" class="control-label"></label>
				<input asp-for="BillingAddress" class="form-control" />
				<span asp-validation-for="BillingAddress" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="BillingCity" class="control-label"></label>
				<input asp-for="BillingCity" class="form-control" />
				<span asp-validation-for="BillingCity" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="BillingPostalCode" class="control-label"></label>
				<input asp-for="BillingPostalCode" class="form-control" />
				<span asp-validation-for="BillingPostalCode" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="BillingCountry" class="control-label"></label>
				<input asp-for="BillingCountry" class="form-control" />
				<span asp-validation-for="BillingCountry" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="ShippingFirstName" class="control-label"></label>
				<input asp-for="ShippingFirstName" class="form-control" />
				<span asp-validation-for="ShippingFirstName" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="ShippingLastName" class="control-label"></label>
				<input asp-for="ShippingLastName" class="form-control" />
				<span asp-validation-for="ShippingLastName" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="ShippingEmail" class="control-label"></label>
				<input asp-for="ShippingEmail" class="form-control" />
				<span asp-validation-for="ShippingEmail" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="ShippingPhone" class="control-label"></label>
				<input asp-for="ShippingPhone" class="form-control" />
				<span asp-validation-for="ShippingPhone" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="ShippingAddress" class="control-label"></label>
				<input asp-for="ShippingAddress" class="form-control" />
				<span asp-validation-for="ShippingAddress" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="ShippingCity" class="control-label"></label>
				<input asp-for="ShippingCity" class="form-control" />
				<span asp-validation-for="ShippingCity" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="ShippingPostalCode" class="control-label"></label>
				<input asp-for="ShippingPostalCode" class="form-control" />
				<span asp-validation-for="ShippingPostalCode" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="ShippingCountry" class="control-label"></label>
				<input asp-for="ShippingCountry" class="form-control" />
				<span asp-validation-for="ShippingCountry" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Message" class="control-label"></label>
				<input asp-for="Message" class="form-control" />
				<span asp-validation-for="Message" class="text-danger"></span>
			</div>
			<div class="form-group">
				<h3>***UserId</h3>
				<label asp-for="UserId" class="control-label"></label>
				<select asp-for="UserId" class="form-control" asp-items="ViewBag.UserId"></select>
			</div>
			<div class="form-group">
				<input type="submit" value="Create" class="btn btn-primary" />
			</div>
		</form>
	</div>
</div>

<div>
	<a asp-action="Index">Back to List</a>
</div>

Movies/Views/AdminOrder/Delete.cshtml
@model Movies.Models.Order

@{
	ViewData["Title"] = "Delete";
}

<h1>Delete order no.@Model.Id</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
	<h4>Order</h4>
	<hr />
	<dl class="row">
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.DateCreated)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.DateCreated)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Total)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Total)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.BillingFirstName)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.BillingFirstName)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.BillingLastName)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.BillingLastName)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.BillingEmail)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.BillingEmail)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.BillingPhone)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.BillingPhone)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.BillingAddress)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.BillingAddress)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.BillingCity)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.BillingCity)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.BillingPostalCode)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.BillingPostalCode)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.BillingCountry)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.BillingCountry)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.ShippingFirstName)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.ShippingFirstName)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.ShippingLastName)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.ShippingLastName)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.ShippingEmail)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.ShippingEmail)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.ShippingPhone)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.ShippingPhone)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.ShippingAddress)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.ShippingAddress)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.ShippingCity)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.ShippingCity)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.ShippingPostalCode)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.ShippingPostalCode)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.ShippingCountry)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.ShippingCountry)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Message)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Message)
		</dd>
	</dl>



	<form asp-action="Delete">
		<input type="hidden" asp-for="Id" />
		<input type="submit" value="Delete" class="btn btn-danger" /> |
		<a asp-action="Index">Back to List</a>
	</form>
</div>

Movies/Views/AdminOrder/Edit.cshtml
@model Movies.Models.Order

@{
	ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Order no. @Model.Id</h4>
 Created on @Model.DateCreated.ToString("dd.MM.yyyy")
<hr />
<form asp-action="Edit">
	<div class="row">
		<div class="col-md-6">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<input type="hidden" asp-for="Id" />
			<input type="hidden" asp-for="UserId" />
			<input type="hidden" asp-for="Total" />
			<input type="hidden" asp-for="DateCreated" />
			<div class="form-group">
				<label asp-for="BillingFirstName" class="control-label"></label>
				<input asp-for="BillingFirstName" class="form-control" />
				<span asp-validation-for="BillingFirstName" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="BillingLastName" class="control-label"></label>
				<input asp-for="BillingLastName" class="form-control" />
				<span asp-validation-for="BillingLastName" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="BillingEmail" class="control-label"></label>
				<input asp-for="BillingEmail" class="form-control" />
				<span asp-validation-for="BillingEmail" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="BillingPhone" class="control-label"></label>
				<input asp-for="BillingPhone" class="form-control" />
				<span asp-validation-for="BillingPhone" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="BillingAddress" class="control-label"></label>
				<input asp-for="BillingAddress" class="form-control" />
				<span asp-validation-for="BillingAddress" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="BillingCity" class="control-label"></label>
				<input asp-for="BillingCity" class="form-control" />
				<span asp-validation-for="BillingCity" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="BillingPostalCode" class="control-label"></label>
				<input asp-for="BillingPostalCode" class="form-control" />
				<span asp-validation-for="BillingPostalCode" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="BillingCountry" class="control-label"></label>
				<input asp-for="BillingCountry" class="form-control" />
				<span asp-validation-for="BillingCountry" class="text-danger"></span>
			</div>
		</div>
		<div class="col-md-6">
			<div class="form-group">
				<label asp-for="ShippingFirstName" class="control-label"></label>
				<input asp-for="ShippingFirstName" class="form-control" />
				<span asp-validation-for="ShippingFirstName" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="ShippingLastName" class="control-label"></label>
				<input asp-for="ShippingLastName" class="form-control" />
				<span asp-validation-for="ShippingLastName" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="ShippingEmail" class="control-label"></label>
				<input asp-for="ShippingEmail" class="form-control" />
				<span asp-validation-for="ShippingEmail" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="ShippingPhone" class="control-label"></label>
				<input asp-for="ShippingPhone" class="form-control" />
				<span asp-validation-for="ShippingPhone" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="ShippingAddress" class="control-label"></label>
				<input asp-for="ShippingAddress" class="form-control" />
				<span asp-validation-for="ShippingAddress" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="ShippingCity" class="control-label"></label>
				<input asp-for="ShippingCity" class="form-control" />
				<span asp-validation-for="ShippingCity" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="ShippingPostalCode" class="control-label"></label>
				<input asp-for="ShippingPostalCode" class="form-control" />
				<span asp-validation-for="ShippingPostalCode" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="ShippingCountry" class="control-label"></label>
				<input asp-for="ShippingCountry" class="form-control" />
				<span asp-validation-for="ShippingCountry" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Message" class="control-label"></label>
				<input asp-for="Message" class="form-control" />
				<span asp-validation-for="Message" class="text-danger"></span>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="form-group mt-2">
			<input type="submit" value="Save" class="btn btn-info" />
			<a asp-action="Index" class="btn btn-dark float-end">Back to List</a>
		</div>
	</div>

</form>
<hr />
<a asp-action="Index" asp-controller="AdminOrderItem" asp-route-id="@Model.Id">Edit order items</a>
<partial name="_OrderItemsPartial" for="@Model.OrderItems" />

Movies/Views/AdminOrder/Index.cshtml
@model IEnumerable<Movies.Models.Order>

@{
	ViewData["Title"] = "Orders";
}

<h1>Orders list</h1>


<table class="table">
	<thead>
		<tr>
			<th>
				@Html.DisplayNameFor(model => model.Id)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.DateCreated)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Total)
			</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model)
		{
			<tr>
				<td>
					@Html.DisplayFor(modelItem => item.Id)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.DateCreated)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Total)
				</td>
				<td>
					<a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
					<a asp-action="Details" asp-route-id="@item.Id">Details</a> |
					<a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
				</td>
			</tr>
		}
	</tbody>
</table>